version: "3"

services:

  dispatch:
    # dispach also serves misc content
    image: nginx
    container_name: project_creativecommons-dispatch
    depends_on:
      - legaltools
      - wordpress
    networks:
      - backend
    ports:
      - "8000:80"
    restart: always
    volumes:
      # config
      - ./config/dispatch_nginx:/etc/nginx/conf.d:ro
      # content (misc)
      - ./mp/docs:/usr/share/nginx/html/platform/toolkit:ro

  legaltools:
    image: nginx
    container_name: project_creativecommons-legaltools
    networks:
      - backend
    ports:
      - "8001:80"
    restart: always
    volumes:
      # config
      - ./cc-legal-tools-data/config/:/etc/nginx/conf.d:ro
      # content
      - ./cc-legal-tools-data/docs/:/usr/share/nginx/html:ro

  wordpress:
    image: wordpress:latest  # https://hub.docker.com/_/wordpress/
    container_name: project_creativecommons-wordpress
    ports:
      - "8002:80"
    volumes:
      #- ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # Full wordpress project
      #- ./wp-app:/var/www/html
      # Plugin development
      - ./wp-plugin-creativecommons-website/:/var/www/html/wp-content/plugins/wp-plugin-creativecommons-website
      # Theme development
      - ./creativecommons-base/:/var/www/html/wp-content/themes/creativecommons-base
      - ./wp-theme-creativecommons.org/:/var/www/html/wp-content/themes/wp-theme-creativecommons.org
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "${DB_NAME:-wordpress_db}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD:-db_password}"
      WORDPRESS_CONFIG_EXTRA: |
        # Use dispatch port by default
        define('WP_HOME', 'http://127.0.0.1:8000');
        define('WP_SITEURL', 'http://127.0.0.1:8000');
    depends_on:
      - database
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_creativecommons-phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-db_password}"
    ports:
      - "8003:80"
    networks:
      - backend

  database:
    build:
      # change db if required in .env file
      context: ./database/${DATABASE:-mariadb}
    container_name: project_creativecommons-database
    ports:
      - "3306:3306"
    volumes:
      #- ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME:-wordpress_db}"
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-db_password}"
    networks:
      - backend

  composer:
    image: composer/composer
    container_name: cc-base-composer
    working_dir: /var/www/html/wp-content/plugins/wp-plugin-creativecommons-website/
    command: "install"
    restart: "no"
    volumes:
      - ./wp-plugin-creativecommons-website/:/var/www/html/wp-content/plugins/wp-plugin-creativecommons-website


volumes:
  db_data:


networks:
  backend:
